import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { addDoc, doc, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { getBlob, ref as storageRef, uploadBytes } from "firebase/storage";
import {
  Activity, CheckCircle2, Database, Eye, FileCheck2, FileText, RefreshCw, ShieldCheck,
  UploadCloud, XCircle, Wrench, Clock3, AlertTriangle, Pencil, Archive,
} from "lucide-react";
import { db, storage } from "@/lib/firebase";
import { useAuth } from "@/contexts/AuthContext";
import { DATA_MODE } from "@/lib/demo-mode";
import { extractStandardCandidate, parseDocument } from "@/lib/api";
import {
  actor, createSharedRecord, datasetCollection, datasetDocId, datasetMode, updateSharedRecord,
  useSharedRecords, writeAudit, type SharedRecord,
} from "@/lib/knowledge-base";
import type {
  CategoryRecord, CertificationRecord, ProductRecord, QcoRecord, RelationshipRecord, StandardRecord, VersionRecord,
} from "@/lib/knowledge-types";
import { AppShell, DataTable, EmptyState, FilterBar, PageHeader, Panel, StatusBadge } from "./ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";

const sourceTypes = ["BIS Standard","BIS Catalogue","Know Your Standard","Gazette / QCO","Government Ministry","Government Portal","Manual Document","API","Other"];
const acquisitionMethods = ["Manual Upload","Web Import","API","Crawler","Other"];
const feedTypes = ["PDF","DOC/DOCX","XLSX","CSV","HTML","API","Other"];
const trustLevels = ["Official BIS","Government","Institutional","Other"];
const frequencies = ["One Time","Manual","Weekly","Monthly","Other"];
const dataContainsOptions = ["Standards","Amendments","Relationships","Certification","QCO","Testing Information","Product Mapping"];

function Shell({ title, description, actions, children }:{title:string;description:string;actions?:React.ReactNode;children:React.ReactNode}) {
  return <AppShell><PageHeader title={title} description={description} actions={actions}/>{children}</AppShell>;
}
function canContribute(role:string){ return ["CONTRIBUTOR","REVIEWER","ADMIN"].includes(role); }
function canReview(role:string){ return ["REVIEWER","ADMIN"].includes(role); }
function ts(value:any){ if (value?.toDate) return value.toDate().toLocaleString(); if (value?.seconds) return new Date(value.seconds*1000).toLocaleString(); return "—"; }
async function viewStoredDocument(path:string){ const blob=await getBlob(storageRef(storage,path)); const url=URL.createObjectURL(blob); window.open(url,"_blank","noopener,noreferrer"); window.setTimeout(()=>URL.revokeObjectURL(url),60_000); }

interface SourceRecord extends SharedRecord {
  sourceName?: string; organization?: string; sourceType?: string; sourceUrl?: string; domain?: string;
  categories?: string[]; dataContains?: string[]; acquisitionMethod?: string; feedType?: string; trustLevel?: string;
  verificationRequired?: boolean; updateFrequency?: string; notes?: string; status?: string; recordsImported?: number;
  recordsVerified?: number; recordsPending?: number; recordsFailed?: number; createdByName?: string; updatedAt?: any;
}

export function SharedSourcesPage(){
  const { user, role }=useAuth();
  const { records, loading, error }=useSharedRecords<SourceRecord>("sources");
  const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [type,setType]=useState("all");
  const [form,setForm]=useState<any>({sourceName:"",organization:"",sourceType:"Manual Document",sourceUrl:"",domain:"",categories:"",dataContains:["Standards"],acquisitionMethod:"Manual Upload",feedType:"PDF",trustLevel:"Other",verificationRequired:true,updateFrequency:"Manual",notes:""});
  const filtered=records.filter(r=>`${r.sourceName||""} ${r.organization||""} ${r.sourceType||""} ${r.domain||""}`.toLowerCase().includes(query.toLowerCase())&&(type==="all"||r.sourceType===type));
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!user||!form.sourceName.trim()||!form.organization.trim())return;await createSharedRecord("sources",{
    sourceName:form.sourceName.trim(), organization:form.organization.trim(), sourceType:form.sourceType, sourceUrl:form.sourceUrl.trim()||null,
    domain:form.domain.trim()||null, categories:form.categories.split(",").map((x:string)=>x.trim()).filter(Boolean), dataContains:form.dataContains,
    acquisitionMethod:form.acquisitionMethod, feedType:form.feedType, trustLevel:form.trustLevel, verificationRequired:form.verificationRequired,
    updateFrequency:form.updateFrequency, notes:form.notes.trim(), status:form.verificationRequired?"PENDING_REVIEW":"ACTIVE",
    lastCheckedAt:null,lastSuccessfulImportAt:null,recordsImported:0,recordsVerified:0,recordsPending:0,recordsFailed:0,
  },user,"SOURCE_CREATED"); setOpen(false); setForm((f:any)=>({...f,sourceName:"",organization:"",sourceUrl:"",domain:"",categories:"",notes:""}));};
  const toggleContains=(v:string)=>setForm((f:any)=>({...f,dataContains:f.dataContains.includes(v)?f.dataContains.filter((x:string)=>x!==v):[...f.dataContains,v]}));
  return <Shell title="Data Sources" description={`Shared ${DATA_MODE} source registry. Sources are visible to authorized users in the same dataset.`} actions={<Button disabled={!canContribute(role)} onClick={()=>setOpen(true)}><Database/>Add Source</Button>}>
    {!canContribute(role)&&<div className="mb-4 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Your role is {role}. Contributor, Reviewer or Admin access is required to register shared sources.</div>}
    {error&&<div className="mb-4 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Firestore listener: {error}</div>}
    <Panel className="overflow-hidden"><FilterBar placeholder="Search source, authority, domain..." onSearch={setQuery} onClear={()=>setType("all")}><Select value={type} onValueChange={setType}><SelectTrigger className="w-full sm:w-52"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All source types</SelectItem>{sourceTypes.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></FilterBar>
      {loading?<p className="text-sm text-muted-foreground">Loading shared sources…</p>:filtered.length?<DataTable columns={["Source","Authority","Type","Trust","Dataset","Status","Contributor","Updated"]} rows={filtered.map(s=>[
        <span className="font-medium">{s.sourceName||"Unnamed source"}</span>,s.organization||"—",s.sourceType||"—",<StatusBadge tone="info">{s.trustLevel||"Unknown"}</StatusBadge>,s.datasetMode||DATA_MODE,<StatusBadge>{s.status||"PENDING_REVIEW"}</StatusBadge>,s.createdByName||"—",ts(s.updatedAt)
      ])}/>:<EmptyState title="No shared sources" description="Register a source to make it available across this dataset."/>}
    </Panel>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-sm:inset-0 max-sm:h-dvh max-sm:max-h-dvh max-sm:w-screen max-sm:translate-x-0 max-sm:translate-y-0 max-sm:rounded-none sm:max-w-3xl"><DialogHeader><DialogTitle>Register Source</DialogTitle><DialogDescription>Register the origin of standards knowledge. This does not make any standard verified.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
      <label className="text-xs font-medium">Source Name *<Input className="mt-1.5" value={form.sourceName} onChange={e=>setForm({...form,sourceName:e.target.value})}/></label>
      <label className="text-xs font-medium">Organization / Authority *<Input className="mt-1.5" value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})}/></label>
      <label className="text-xs font-medium">Source Type *<Select value={form.sourceType} onValueChange={v=>setForm({...form,sourceType:v})}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent>{sourceTypes.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>
      <label className="text-xs font-medium">Source URL<Input className="mt-1.5" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></label>
      <label className="text-xs font-medium">Domain<Input className="mt-1.5" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/></label>
      <label className="text-xs font-medium">Categories <span className="font-normal text-muted-foreground">(comma separated)</span><Input className="mt-1.5" value={form.categories} onChange={e=>setForm({...form,categories:e.target.value})}/></label>
      <label className="text-xs font-medium">Acquisition Method<Select value={form.acquisitionMethod} onValueChange={v=>setForm({...form,acquisitionMethod:v})}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent>{acquisitionMethods.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>
      <label className="text-xs font-medium">Document / Feed Type<Select value={form.feedType} onValueChange={v=>setForm({...form,feedType:v})}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent>{feedTypes.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>
      <label className="text-xs font-medium">Authority / Trust Level<Select value={form.trustLevel} onValueChange={v=>setForm({...form,trustLevel:v})}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent>{trustLevels.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>
      <label className="text-xs font-medium">Update Frequency<Select value={form.updateFrequency} onValueChange={v=>setForm({...form,updateFrequency:v})}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent>{frequencies.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>
      <div className="sm:col-span-2"><p className="mb-2 text-xs font-medium">Data Contains</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{dataContainsOptions.map(v=><label key={v} className="flex items-center gap-2 rounded-md border p-2 text-xs"><Checkbox checked={form.dataContains.includes(v)} onCheckedChange={()=>toggleContains(v)}/>{v}</label>)}</div></div>
      <label className="flex items-center gap-2 text-xs font-medium"><Checkbox checked={form.verificationRequired} onCheckedChange={v=>setForm({...form,verificationRequired:Boolean(v)})}/>Verification Required</label>
      <label className="text-xs font-medium sm:col-span-2">Description / Notes<Textarea className="mt-1.5" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
      <div className="flex flex-col-reverse gap-2 sm:col-span-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">Register Source</Button></div>
    </form></DialogContent></Dialog>
  </Shell>;
}

interface IngestionJob extends SharedRecord { fileName?:string; sourceId?:string; sourceName?:string; status?:string; progress?:number; createdByName?:string; createdAt?:any; recordsExtracted?:number; warnings?:string[]; errors?:string[]; reviewStatus?:string; documentStored?:boolean; }

export function SharedIngestionPage(){
 const {user,role}=useAuth(); const input=useRef<HTMLInputElement>(null); const {records,loading,error}=useSharedRecords<IngestionJob>("ingestionJobs","createdAt"); const {records:sources}=useSharedRecords<SourceRecord>("sources"); const {records:standards}=useSharedRecords<any>("standards");
 const [sourceId,setSourceId]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [queryText,setQueryText]=useState("");
 const start=async(file?:File)=>{if(!file||!user)return;if(!sourceId){setMessage("Select a registered source before importing.");return;}setBusy(true);setMessage("");const source=sources.find(s=>s.id===sourceId);let jobId="";
  try{
   jobId=await createSharedRecord("ingestionJobs",{fileName:file.name,fileSize:file.size,sourceId,sourceName:source?.sourceName||"Registered source",status:"UPLOADING",progress:8,recordsExtracted:0,warnings:[],errors:[],reviewStatus:"PENDING",documentStored:false},user,"DOCUMENT_UPLOAD_STARTED");
   const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"_").slice(-160)||"document";
   const objectPath=`datasets/${datasetDocId}/ingestion/${user.uid}/${jobId}/${safeName}`;
   const objectRef=storageRef(storage,objectPath);
   await uploadBytes(objectRef,file,{contentType:file.type||undefined,customMetadata:{datasetMode:datasetMode,sourceId,jobId,ownerUid:user.uid}});
   await updateSharedRecord("ingestionJobs",jobId,{status:"EXTRACTING",progress:20,documentStored:true,storagePath:objectPath},user,"DOCUMENT_UPLOADED");
   const parsed=await parseDocument(file); await updateSharedRecord("ingestionJobs",jobId,{status:"AI_PROCESSING",progress:48,characterCount:parsed.characterCount},user,"INGESTION_UPDATED");
   const extracted=await extractStandardCandidate(parsed.fullText,file.name); const candidate=extracted.candidate;
   const identity=(candidate.identity||{}) as Record<string,any>; const designation=String(identity.designation||candidate.standardId||"").trim(); const standardNumber=String(identity.standardNumber||"").trim();
   const normalize=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g," ").trim(); const normalizedText=normalize(parsed.fullText);
   const identityToken=normalize(designation||standardNumber); const identitySupported=Boolean(identityToken)&&normalizedText.includes(identityToken); const requiredOk=Boolean(designation||standardNumber)&&Boolean(candidate.title);
   const duplicate=standards.some((r:any)=>normalize(String(r.standardId||r.identity?.designation||r.isNumber||""))===normalize(designation||standardNumber));
   const validation={identityValidation:identitySupported?"PASS":requiredOk?"WARNING":"FAIL",schemaValidation:requiredOk?"PASS":"WARNING",sourceValidation:source?"PASS":"FAIL",duplicateCheck:duplicate?"WARNING":"PASS",versionCheck:"UNKNOWN",relationshipCheck:"UNKNOWN",certificationCheck:"UNKNOWN",qcoCheck:"UNKNOWN",requiredFieldCheck:requiredOk?"PASS":"WARNING"};
   const warnings=[...parsed.warnings.map(x=>typeof x==="string"?x:JSON.stringify(x)),...(identitySupported?[]:["Extracted standard identity was not deterministically confirmed in normalized source text."]),...(duplicate?["A standard with the same identity already exists in the selected dataset."]:[])];
   const a=actor(user); const submissionRef=await addDoc(datasetCollection("submissions"),{candidate,validation,originalDocument:{fileName:file.name,storageUrl:null,storagePath:objectPath,documentStored:true,characterCount:parsed.characterCount},sourceId,sourceName:source?.sourceName||null,status:"PENDING",verificationStatus:"PENDING",reviewDecision:null,reviewReason:null,dataMode:datasetMode,domain:candidate.classification?.domain||null,category:candidate.classification?.category||null,createdBy:a.userId,createdByName:a.userName,createdAt:serverTimestamp(),updatedBy:a.userId,updatedByName:a.userName,updatedAt:serverTimestamp(),aiProvider:extracted.provider,aiModel:extracted.model,ingestionJobId:jobId,warnings});
   await updateSharedRecord("ingestionJobs",jobId,{status:duplicate?"DUPLICATE_FOUND":"NEEDS_REVIEW",progress:100,recordsExtracted:1,reviewStatus:"PENDING",submissionId:submissionRef.id,warnings},user,"INGESTION_COMPLETED");
   if(source){await updateSharedRecord("sources",source.id,{lastCheckedAt:serverTimestamp(),lastSuccessfulImportAt:serverTimestamp(),recordsImported:Number(source.recordsImported||0)+1,recordsPending:Number(source.recordsPending||0)+1,status:"ACTIVE"},user,"SOURCE_UPDATED");}
   await writeAudit(user,"SUBMISSION_CREATED","SUBMISSION",submissionRef.id,{ingestionJobId:jobId,sourceId,category:candidate.classification?.category||null});
   setMessage(`${file.name} was extracted and sent to human review. It is not verified knowledge yet.`);
  }catch(e){const msg=e instanceof Error?e.message:"Ingestion failed";setMessage(msg);if(jobId)try{await updateSharedRecord("ingestionJobs",jobId,{status:"FAILED",errors:[msg],progress:100},user,"INGESTION_FAILED")}catch{} }finally{setBusy(false);if(input.current)input.current.value="";}};
 const filtered=records.filter(r=>`${r.id} ${r.fileName||""} ${r.sourceName||""}`.toLowerCase().includes(queryText.toLowerCase()));
 return <Shell title="Data Ingestion" description="Upload → Firebase Storage → current parser → AI extraction → validation → pending human review. Upload never means verified." actions={<><input ref={input} type="file" className="hidden" accept=".pdf,.doc,.docx,.xlsx,.csv,.html,.htm,.txt,.md,.pptx" onChange={e=>void start(e.target.files?.[0])}/><Button disabled={busy||!canContribute(role)||!sourceId} onClick={()=>input.current?.click()}><UploadCloud/>{busy?"Processing…":"New Import"}</Button></>}>
  <div className="mb-4 grid gap-3 rounded-md border bg-muted/25 p-4 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-xs font-medium">Registered Source<Select value={sourceId} onValueChange={setSourceId}><SelectTrigger className="mt-1.5"><SelectValue placeholder="Select source before upload"/></SelectTrigger><SelectContent>{sources.map(s=><SelectItem key={s.id} value={s.id}>{s.sourceName||s.id}</SelectItem>)}</SelectContent></Select></label><StatusBadge tone="warning">Human review required</StatusBadge></div>
  {!canContribute(role)&&<div className="mb-4 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Contributor access or above is required for ingestion.</div>}{message&&<div className="mb-4 rounded-md border bg-card p-3 text-xs">{message}</div>}{error&&<div className="mb-4 text-xs text-warning">{error}</div>}
  <Panel title="Ingestion Jobs" description="Statuses reflect persisted Firestore jobs, not component-only simulation."><FilterBar onSearch={setQueryText} placeholder="Search job, source or file…"/>{loading?<p className="text-sm text-muted-foreground">Loading ingestion jobs…</p>:filtered.length?<DataTable columns={["Job ID","File","Source","Stage","Progress","Submitted By","Submitted","Review"]} rows={filtered.map(r=>[r.id,r.fileName||"—",r.sourceName||"—",<StatusBadge>{r.status||"UPLOADED"}</StatusBadge>,`${r.progress||0}%`,r.createdByName||"—",ts(r.createdAt),r.reviewStatus||"—"])}/>:<EmptyState title="No ingestion jobs" description="Choose a shared source and upload a supported document."/>}</Panel>
 </Shell>;
}

interface Submission extends SharedRecord { candidate?:Record<string,any>; validation?:Record<string,string>; originalDocument?:Record<string,any>; sourceId?:string; sourceName?:string; status?:string; createdByName?:string; createdAt?:any; category?:string; domain?:string; reviewReason?:string; }

export function SharedReviewPage(){
 const {user,role}=useAuth(); const {records,loading,error}=useSharedRecords<Submission>("submissions","createdAt"); const [selected,setSelected]=useState<Submission|null>(null); const [editing,setEditing]=useState(false); const [jsonText,setJsonText]=useState(""); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false);
 const pending=records.filter(r=>["PENDING","NEEDS_REVIEW","NEEDS_CORRECTION"].includes(String(r.status||"PENDING")));
 const open=(r:Submission)=>{setSelected(r);setJsonText(JSON.stringify(r.candidate||{},null,2));setReason(r.reviewReason||"");setEditing(false)};
 const decision=async(kind:"APPROVE"|"REJECT"|"CORRECTION")=>{if(!selected||!user||!canReview(role))return;setBusy(true);try{let candidate=selected.candidate||{};if(editing){candidate=JSON.parse(jsonText)}const a=actor(user);if(kind==="APPROVE"){
   const identity=(candidate.identity||{}) as Record<string,any>; const sid=String(candidate.standardId||identity.designation||identity.standardNumber||"").trim(); if(!sid)throw new Error("Cannot approve: standard identity is not established. Edit the candidate or request correction.");
   const safeId=sid.replace(/\//g,"_").replace(/\s+/g,"_"); await setDoc(doc(db,"datasets",datasetDocId,"standards",safeId),{...candidate,standardId:sid,dataMode:datasetMode,provenance:{...(candidate.provenance||{}),sourceId:selected.sourceName||null,uploadedBy:selected.createdBy||null,uploadedByName:selected.createdByName||null,uploadedAt:selected.createdAt||null,reviewedBy:a.userId,reviewedByName:a.userName,reviewedAt:serverTimestamp(),verificationStatus:"VERIFIED"},verificationStatus:"VERIFIED",updatedAt:serverTimestamp(),updatedBy:a.userId,updatedByName:a.userName},{merge:true});
   await updateDoc(doc(db,"datasets",datasetDocId,"submissions",selected.id),{candidate,status:"APPROVED",verificationStatus:"VERIFIED",reviewDecision:"APPROVE",reviewReason:reason||null,reviewedBy:a.userId,reviewedByName:a.userName,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()}); await writeAudit(user,"STANDARD_APPROVED","STANDARD",safeId,{submissionId:selected.id,category:selected.category||null}); if(selected.sourceId){const sourceDoc=(await import("firebase/firestore")).getDoc; const snap=await sourceDoc(doc(db,"datasets",datasetDocId,"sources",selected.sourceId)); const src=snap.data()||{}; await updateSharedRecord("sources",selected.sourceId,{recordsPending:Math.max(0,Number(src.recordsPending||0)-1),recordsVerified:Number(src.recordsVerified||0)+1,status:"ACTIVE"},user,"SOURCE_UPDATED");}
  }else{const status=kind==="REJECT"?"REJECTED":"NEEDS_CORRECTION";await updateDoc(doc(db,"datasets",datasetDocId,"submissions",selected.id),{candidate,status,verificationStatus:status,reviewDecision:kind,reviewReason:reason||null,reviewedBy:a.userId,reviewedByName:a.userName,reviewedAt:serverTimestamp(),updatedAt:serverTimestamp()});await writeAudit(user,kind==="REJECT"?"STANDARD_REJECTED":"STANDARD_CORRECTED","SUBMISSION",selected.id,{reason}); if(kind==="REJECT"&&selected.sourceId){const sourceDoc=(await import("firebase/firestore")).getDoc; const snap=await sourceDoc(doc(db,"datasets",datasetDocId,"sources",selected.sourceId)); const src=snap.data()||{}; await updateSharedRecord("sources",selected.sourceId,{recordsPending:Math.max(0,Number(src.recordsPending||0)-1)},user,"SOURCE_UPDATED");}}
  setSelected(null);
 }catch(e){alert(e instanceof Error?e.message:"Review action failed")}finally{setBusy(false)}};
 return <Shell title="Review Queue" description="Human review gate for candidate knowledge. Review opens details; records are never deleted merely by opening them.">
  {!canReview(role)&&<div className="mb-4 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Your role is {role}. Reviewer or Admin access is required to make review decisions.</div>}{error&&<div className="mb-4 text-xs text-warning">{error}</div>}
  <Panel>{loading?<p className="text-sm text-muted-foreground">Loading review submissions…</p>:pending.length?<DataTable columns={["Submission","Candidate","Domain","Category","Submitted By","Submitted","Status","Action"]} rows={pending.map(r=>[r.id,String(r.candidate?.identity?.designation||r.candidate?.title||"Unidentified candidate"),r.domain||"—",r.category||"—",r.createdByName||"—",ts(r.createdAt),<StatusBadge>{r.status||"PENDING"}</StatusBadge>,<Button size="sm" variant="outline" onClick={()=>open(r)}><Eye/>Review</Button>])}/>:<EmptyState title="No pending submissions" description="Processed decisions remain in Firestore for audit history."/>}</Panel>
  <Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="h-dvh max-h-dvh w-screen max-w-none translate-x-[-50%] translate-y-[-50%] rounded-none sm:h-[92dvh] sm:max-h-[92dvh] sm:w-[calc(100vw-2rem)] sm:max-w-4xl sm:rounded-lg"><DialogHeader><DialogTitle>Review Record</DialogTitle><DialogDescription>{selected?.originalDocument?.fileName||"Candidate record"} · {selected?.sourceName||"Unknown source"} · {DATA_MODE}</DialogDescription></DialogHeader>{selected&&<div className="space-y-5 pb-24 sm:pb-4">
    <Panel title="Original Document"><div className="grid gap-2 text-sm sm:grid-cols-2"><span>Submitted by: <strong>{selected.createdByName||"—"}</strong></span><span>Submitted: <strong>{ts(selected.createdAt)}</strong></span><span>Domain: <strong>{selected.domain||"—"}</strong></span><span>Category: <strong>{selected.category||"—"}</strong></span></div>{selected.originalDocument?.storagePath&&<Button className="mt-3" variant="outline" onClick={()=>void viewStoredDocument(String(selected.originalDocument?.storagePath))}><FileText/>View Document</Button>}</Panel>
    <Panel title="AI / System Extracted Data" action={<Button size="sm" variant="outline" onClick={()=>setEditing(v=>!v)}><Pencil/>{editing?"Preview":"Edit Extracted Data"}</Button>}>{editing?<Textarea value={jsonText} onChange={e=>setJsonText(e.target.value)} className="min-h-[340px] font-mono text-xs"/>:<pre className="max-h-[420px] overflow-auto whitespace-pre-wrap break-words rounded-md bg-muted p-3 text-xs">{JSON.stringify(selected.candidate||{},null,2)}</pre>}</Panel>
    <Panel title="Validation Results"><div className="grid gap-2 sm:grid-cols-2">{Object.entries(selected.validation||{}).map(([k,v])=><div key={k} className="flex items-center justify-between gap-3 rounded-md border p-3 text-xs"><span className="break-words">{k.replace(/([A-Z])/g," $1")}</span><StatusBadge>{v}</StatusBadge></div>)}</div></Panel>
    <Panel title="Reviewer Notes"><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason / correction instructions / approval notes"/></Panel>
    <div className="sticky bottom-0 z-10 flex flex-col gap-2 border-t bg-background/95 p-3 backdrop-blur sm:flex-row sm:justify-end"><Button variant="destructive" disabled={busy||!canReview(role)} onClick={()=>void decision("REJECT")}><XCircle/>Reject</Button><Button variant="outline" disabled={busy||!canReview(role)} onClick={()=>void decision("CORRECTION")}><Wrench/>Request Correction</Button><Button disabled={busy||!canReview(role)} onClick={()=>void decision("APPROVE")}><CheckCircle2/>Approve</Button></div>
  </div>}</DialogContent></Dialog>
 </Shell>;
}

interface AuditRecord extends SharedRecord { action?:string; entityType?:string; entityId?:string; dataset?:string; userName?:string; timestamp?:any; metadata?:Record<string,any>; }
export function DataActivityPage(){
 const {records,loading,error}=useSharedRecords<AuditRecord>("auditLogs","timestamp");
 const [q,setQ]=useState(""); const [action,setAction]=useState("all"); const [userFilter,setUserFilter]=useState("all"); const [domain,setDomain]=useState("all"); const [category,setCategory]=useState("all"); const [dataset,setDataset]=useState("all"); const [status,setStatus]=useState("all"); const [date,setDate]=useState("");
 const unique=(values:(string|undefined)[])=>[...new Set(values.filter(Boolean) as string[])].sort();
 const actions=useMemo(()=>unique(records.map(r=>r.action)),[records]); const users=useMemo(()=>unique(records.map(r=>r.userName)),[records]); const domains=useMemo(()=>unique(records.map(r=>r.metadata?.domain)),[records]); const categories=useMemo(()=>unique(records.map(r=>r.metadata?.category)),[records]); const statuses=useMemo(()=>unique(records.map(r=>r.metadata?.status)),[records]);
 const filtered=records.filter(r=>{const text=`${r.userName||""} ${r.action||""} ${r.entityType||""} ${r.entityId||""} ${r.metadata?.category||""} ${r.metadata?.domain||""}`.toLowerCase();const day=r.timestamp?.toDate?.()?.toISOString?.().slice(0,10)||"";return text.includes(q.toLowerCase())&&(action==="all"||r.action===action)&&(userFilter==="all"||r.userName===userFilter)&&(domain==="all"||r.metadata?.domain===domain)&&(category==="all"||r.metadata?.category===category)&&(dataset==="all"||(r.dataset||DATA_MODE)===dataset)&&(status==="all"||r.metadata?.status===status)&&(!date||day===date)});
 const clear=()=>{setAction("all");setUserFilter("all");setDomain("all");setCategory("all");setDataset("all");setStatus("all");setDate("")};
 return <Shell title="Data Activity" description="Immutable shared-data activity from Firestore audit logs."><Panel><FilterBar onSearch={setQ} onClear={clear} advancedContent={<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-medium">User<Select value={userFilter} onValueChange={setUserFilter}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All users</SelectItem>{users.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="text-xs font-medium">Domain<Select value={domain} onValueChange={setDomain}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All domains</SelectItem>{domains.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="text-xs font-medium">Category<Select value={category} onValueChange={setCategory}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="text-xs font-medium">Dataset<Select value={dataset} onValueChange={setDataset}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All datasets</SelectItem><SelectItem value="DEMO">DEMO</SelectItem><SelectItem value="REAL">REAL</SelectItem></SelectContent></Select></label><label className="text-xs font-medium">Status<Select value={status} onValueChange={setStatus}><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="text-xs font-medium">Date<Input type="date" className="mt-1.5" value={date} onChange={e=>setDate(e.target.value)}/></label></div>}><Select value={action} onValueChange={setAction}><SelectTrigger className="w-full sm:w-56"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All actions</SelectItem>{actions.map(a=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select></FilterBar>{error&&<p className="mb-3 text-xs text-warning">{error}</p>}{loading?<p className="text-sm text-muted-foreground">Loading activity…</p>:filtered.length?<DataTable columns={["Time","User","Action","Entity","Domain","Category","Dataset","Status"]} rows={filtered.map(r=>[ts(r.timestamp),r.userName||"—",<StatusBadge tone="info">{r.action||"—"}</StatusBadge>,`${r.entityType||"—"} · ${r.entityId||"—"}`,r.metadata?.domain||"—",r.metadata?.category||"—",r.dataset||DATA_MODE,r.metadata?.status||"—"])}/>:<EmptyState title="No audit activity" description="Shared-data changes will appear here automatically."/>}</Panel></Shell>;
}


export function KnowledgeBaseStatusPanel(){
 const standards=useSharedRecords("standards"); const products=useSharedRecords("products"); const categories=useSharedRecords("categories"); const relationships=useSharedRecords("relationships"); const certifications=useSharedRecords("certifications"); const qcos=useSharedRecords("qcos"); const amendments=useSharedRecords("amendments"); const submissions=useSharedRecords<Submission>("submissions"); const jobs=useSharedRecords<IngestionJob>("ingestionJobs"); const audit=useSharedRecords<AuditRecord>("auditLogs","timestamp");
 const latest=audit.records[0]; const stats=[['Dataset',DATA_MODE],['Total Standards',standards.records.length],['Verified Standards',standards.records.filter((r:any)=>r.verificationStatus==='VERIFIED'||r.provenance?.verificationStatus==='VERIFIED').length],['Products',products.records.length],['Categories',categories.records.length],['Relationships',relationships.records.length],['Certifications',certifications.records.length],['QCO Records',qcos.records.length],['Amendments',amendments.records.length],['Pending Review',submissions.records.filter(r=>r.status==='PENDING'||r.status==='NEEDS_REVIEW').length],['Needs Correction',submissions.records.filter(r=>r.status==='NEEDS_CORRECTION').length],['Failed Ingestion Jobs',jobs.records.filter(r=>r.status==='FAILED').length],['Last Data Update',latest?ts(latest.timestamp):'—'],['Last Contributor',latest?.userName||'—']];
 return <Panel title="Knowledge Base Status" description="Live shared knowledge statistics for the selected dataset."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stats.map(([k,v])=><div key={String(k)} className="rounded-md border p-3"><p className="text-[11px] uppercase text-muted-foreground">{k}</p><p className="mt-1 break-words text-lg font-semibold text-navy">{v}</p></div>)}</div></Panel>;
}


export function SystemDiagnosticsPage(){
 const {role}=useAuth(); const [state,setState]=useState<any>({loading:true});
 const run=async()=>{setState({loading:true});const api=await import("@/lib/api");const checkedAt=new Date().toLocaleString();let backend:any=null,model:any=null,firestore:any=null;try{backend=await api.checkBackendHealth()}catch(e){backend={error:e instanceof Error?e.message:"Offline"}}try{model=await api.checkModelConnection()}catch(e){model={error:e instanceof Error?e.message:"Offline"}}try{firestore=await api.checkFirestoreHealth()}catch(e){firestore={error:e instanceof Error?e.message:"Unavailable"}}setState({loading:false,backend,model,firestore,checkedAt})};
 useEffect(()=>{void run();},[]);
 if(role!=="ADMIN")return <Shell title="System Diagnostics" description="Administrative runtime health."><EmptyState title="Restricted" description="Admin role is required to view system diagnostics."/></Shell>;
 const line=(label:string,value:string,tone:any)=><div className="flex items-center justify-between gap-3 border-b py-3 text-sm"><span>{label}</span><StatusBadge tone={tone}>{value}</StatusBadge></div>;
 const pipelineMode = localStorage.getItem("bsai.pipeline") === "pro" ? "Pro Pipeline (Local Qwen Solo)" : "Basic Pipeline (NVIDIA + Gemma)";
 return <Shell title="System Diagnostics" description="Live runtime health checks separated from normal knowledge-base status." actions={<Button variant="outline" onClick={()=>void run()}><RefreshCw/>Run Health Check</Button>}><Panel>{state.loading?<p className="text-sm text-muted-foreground">Checking services…</p>:<div>
  {line("Pipeline Mode",pipelineMode,"info")}
  {line("Backend",state.backend?.error?"Offline":"Online",state.backend?.error?"danger":"success")}
  {line("AI Provider",state.model?.provider||state.backend?.aiProvider||"Unknown",state.model?.error?"danger":"info")}
  {line("AI Model",state.model?.model||"Unavailable",state.model?.error?"danger":"success")}
  {line("Firestore",state.firestore?.ok?"Connected":"Error",state.firestore?.ok?"success":"danger")}
  {line("Document Processing",state.backend?.documentParser?`Ready · ${state.backend.documentParser}`:"Error",state.backend?.documentParser?"success":"danger")}
  {line("Vector Search","Not configured","warning")}
  <p className="mt-4 text-xs text-muted-foreground">Last health check: {state.checkedAt}</p>
 </div>}</Panel></Shell>;
}

function readable(value?:string|null){ return String(value||"").replace(/_/g," ").replace(/\s+/g," ").trim(); }
function searchText(...values:unknown[]){
 return values.flatMap(v=>Array.isArray(v)?v:[v]).filter(Boolean).map(v=>String(v)).join(" ").toLowerCase();
}
function labelForStandard(r:StandardRecord){ return r.isNumber || (r as any).identity?.designation || r.standardId || r.id; }
function datasetBadge(r:{dataMode?:string;verificationStatus?:string}){ return r.dataMode||DATA_MODE; }
function mandatoryLabel(value:boolean|null|undefined|string){ if(value===true)return "Yes";if(value===false)return "No";if(value==null)return "Not established";return readable(String(value)); }
function FieldValue({label,value}:{label:string;value:React.ReactNode}){return <div className="min-w-0"><p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">{label}</p><div className="mt-1 break-words text-sm font-medium">{value??"—"}</div></div>}
function ChipList({items}:{items?:string[]}){if(!items?.length)return <span className="text-sm text-muted-foreground">None recorded</span>;return <div className="flex flex-wrap gap-1.5">{items.map((item,i)=><span key={`${item}-${i}`} className="max-w-full break-words rounded-full border bg-muted/35 px-2.5 py-1 text-xs">{item}</span>)}</div>}
function RecordBadge({record}:{record:{dataMode?:string;verificationStatus?:string}}){return <StatusBadge>{datasetBadge(record)}</StatusBadge>}
function standardHref(id?:string){return id?`/standards/${encodeURIComponent(id)}`:"#"}

export function SharedStandardsPage(){
 const {records,loading,error}=useSharedRecords<StandardRecord>("standards"); const [q,setQ]=useState(""); const [status,setStatus]=useState("all");
 const filtered=records.filter(r=>searchText(r.standardId,r.isNumber,r.title,r.productFamily,r.category,r.domain,r.classification?.domain,r.classification?.category,r.classification?.subcategory,r.scope?.includedProducts).includes(q.toLowerCase())&&(status==="all"||String(r.verificationStatus||(typeof r.status==="object"?r.status?.state:r.status)||"").toLowerCase()===status));
 return <Shell title="Standards Explorer" description={`Shared ${DATA_MODE} standards knowledge from Firestore.`}><Panel><FilterBar placeholder="Search designation, title, product, category…" onSearch={setQ} onClear={()=>setStatus("all")}><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full sm:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="verified">Verified</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="demo">Demo</SelectItem><SelectItem value="needs_review">Needs Review</SelectItem></SelectContent></Select></FilterBar>{error&&<div className="mb-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load {DATA_MODE} standards. {error}</div>}{loading?<p className="text-sm text-muted-foreground">Loading shared standards…</p>:filtered.length?<DataTable columns={["Designation","Title","Domain","Category","Product Family","Status","Dataset"]} rows={filtered.map(r=>[<a className="font-semibold text-primary hover:underline" href={standardHref(r.standardId||r.id)}>{labelForStandard(r)}</a>,r.title||"—",r.classification?.domain||r.domain||"—",r.classification?.category||r.category||"—",readable(r.productFamily||r.classification?.productGroup)||"—",<StatusBadge>{r.verificationStatus||(typeof r.status==="object"?r.status?.state:r.status)||"UNKNOWN"}</StatusBadge>,r.dataMode||DATA_MODE])}/>:<EmptyState title="No shared standards" description="No standards are currently available in the selected dataset."/>}</Panel></Shell>;
}

export function SharedStandardDetailsPage(){
 const requested=decodeURIComponent(window.location.pathname.split("/").pop()||""); const {records,loading,error}=useSharedRecords<StandardRecord>("standards"); const r=records.find(x=>String(x.standardId||x.id)===requested);
 if(loading)return <Shell title="Standard Details" description="Resolving shared Firestore record…"><Panel><p className="text-sm text-muted-foreground">Loading…</p></Panel></Shell>;
 if(error)return <Shell title="Standard Details" description={`Requested record: ${requested}`}><Panel><div className="rounded-md border border-warning/25 bg-warning-soft p-3 text-sm text-warning">Unable to load the selected dataset. {error}</div></Panel></Shell>;
 if(!r)return <Shell title="Standard Details" description={`Requested record: ${requested}`}><EmptyState title="Standard Not Found" description="No exact standard record exists in the selected shared dataset. No fallback was substituted."/></Shell>;
 const provenance=(r.provenance||{}) as Record<string,any>;
 return <Shell title={labelForStandard(r)} description={r.title||"Shared standard record"}><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Identity & Classification"><div className="grid gap-4 sm:grid-cols-2"><FieldValue label="Standard ID" value={r.standardId||r.id}/><FieldValue label="Domain" value={r.classification?.domain||r.domain||"—"}/><FieldValue label="Category" value={r.classification?.category||r.category||"—"}/><FieldValue label="Product Family" value={readable(r.classification?.productGroup||r.productFamily)||"—"}/><FieldValue label="Verification" value={<StatusBadge>{r.verificationStatus||provenance.verificationStatus||"UNKNOWN"}</StatusBadge>}/><FieldValue label="Dataset" value={<RecordBadge record={r}/>}/></div></Panel><Panel title="Provenance"><div className="grid gap-4"><FieldValue label="Source" value={provenance.sourceType||provenance.sourceId||"Not provided"}/><FieldValue label="Reviewed By" value={provenance.reviewedByName||"Not provided"}/><FieldValue label="Verification" value={provenance.verificationStatus||r.verificationStatus||"Not provided"}/></div></Panel></div><Panel title="Scope & Applicability"><p className="break-words text-sm leading-6">{r.scope?.summary||"No scope summary is stored for this shared record."}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><p className="mb-2 text-xs font-medium text-muted-foreground">Included Products</p><ChipList items={r.scope?.includedProducts}/></div><div><p className="mb-2 text-xs font-medium text-muted-foreground">Applications</p><ChipList items={r.scope?.applications}/></div><div><p className="mb-2 text-xs font-medium text-muted-foreground">Testing Requirements</p><ChipList items={r.testingRequirements}/></div><div><p className="mb-2 text-xs font-medium text-muted-foreground">Requirements Covered</p><ChipList items={r.requirementsCovered}/></div></div></Panel></Shell>;
}

function ProductCard({r}:{r:ProductRecord}){return <div className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-navy">{r.productName||"Unnamed product"}</h3><p className="mt-1 break-words text-xs text-muted-foreground">{r.domain||"Unclassified domain"}</p></div><RecordBadge record={r}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><FieldValue label="Category" value={r.category||"—"}/><FieldValue label="Product Family" value={readable(r.productFamily)||"—"}/><FieldValue label="Primary Standard" value={r.primaryStandardId?<a className="text-primary hover:underline" href={standardHref(r.primaryStandardId)}>{r.primaryStandardId}</a>:"Not linked"}/><FieldValue label="Status" value={r.active===false?"Inactive":"Active"}/></div><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Aliases</p><ChipList items={r.aliases}/></div><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Materials</p><ChipList items={r.materials}/></div><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Applications</p><ChipList items={r.applications}/></div><div className="mt-4 flex flex-wrap gap-2">{r.primaryStandardId&&<Button size="sm" variant="outline" asChild><a href={standardHref(r.primaryStandardId)}>View Standard</a></Button>}{r.categoryId&&<Button size="sm" variant="outline" asChild><a href={`/categories?category=${encodeURIComponent(r.categoryId)}`}>View Category</a></Button>}<Button size="sm" variant="outline" asChild><a href={`/relationships?product=${encodeURIComponent(r.productFamily||r.productId||r.id)}`}>View Relationships</a></Button></div></div>}

export function SharedProductsPage(){const {records,loading,error}=useSharedRecords<ProductRecord>("products");const [q,setQ]=useState("");const filtered=records.filter(r=>searchText(r.productName,r.domain,r.category,r.productFamily,r.aliases,r.materials,r.applications,r.primaryStandardId).includes(q.toLowerCase()));return <Shell title="Product Explorer" description="Shared product taxonomy and aliases for the selected dataset."><Panel><FilterBar placeholder="Search product, alias, category or standard…" onSearch={setQ}/>{error&&<div className="mb-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load {DATA_MODE} products. {error}</div>}{loading?<p className="text-sm text-muted-foreground">Loading shared products…</p>:filtered.length?<div className="grid gap-4 lg:grid-cols-2">{filtered.map(r=><ProductCard key={r.id} r={r}/>)}</div>:<EmptyState title="No products available" description={`No shared products are currently available in ${DATA_MODE}.`}/>}</Panel></Shell>}

function CategoryCard({r,products,standards}:{r:CategoryRecord;products:ProductRecord[];standards:StandardRecord[]}){const productCount=products.filter(p=>p.categoryId===r.categoryId||p.category===r.name).length;const standardCount=standards.filter(s=>s.category===r.name||s.classification?.category===r.name).length;return <div className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-navy">{r.name||"Unnamed category"}</h3><p className="mt-1 text-xs text-muted-foreground">{r.domain||"Unclassified domain"}</p></div><RecordBadge record={r}/></div><p className="mt-3 break-words text-sm leading-6">{r.description||"No description recorded."}</p><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Aliases</p><ChipList items={r.aliases}/></div><div className="mt-4 grid grid-cols-3 gap-3"><FieldValue label="Products" value={productCount}/><FieldValue label="Standards" value={standardCount}/><FieldValue label="Status" value={r.active===false?"Inactive":"Active"}/></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" asChild><a href={`/products?category=${encodeURIComponent(r.categoryId||r.name||"")}`}>View Products</a></Button><Button size="sm" variant="outline" asChild><a href={`/standards?category=${encodeURIComponent(r.name||"")}`}>View Standards</a></Button></div></div>}

export function SharedCategoriesPage(){const categories=useSharedRecords<CategoryRecord>("categories");const products=useSharedRecords<ProductRecord>("products");const standards=useSharedRecords<StandardRecord>("standards");const [q,setQ]=useState("");const filtered=categories.records.filter(r=>searchText(r.name,r.domain,r.description,r.aliases).includes(q.toLowerCase()));const error=categories.error||products.error||standards.error;return <Shell title="Categories" description="Shared category metadata. Categories do not vary by browser or user."><Panel><FilterBar placeholder="Search category, domain or alias…" onSearch={setQ}/>{error&&<div className="mb-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load complete category data. {error}</div>}{categories.loading?<p className="text-sm text-muted-foreground">Loading categories…</p>:filtered.length?<div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><CategoryCard key={r.id} r={r} products={products.records} standards={standards.records}/>)}</div>:<EmptyState title="No categories available" description={`No shared categories are currently available in ${DATA_MODE}.`}/>}</Panel></Shell>}

function RelationshipCard({r}:{r:RelationshipRecord}){const from=r.fromStandard||r.fromStandardId||"Unknown source standard";const to=r.toStandard||r.toStandardId||"Unknown related standard";return <div className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-sm font-semibold text-navy">{from}</p><div className="my-2 text-xs text-muted-foreground">↓</div><StatusBadge tone="info">{readable(r.relationshipType)||"RELATED"}</StatusBadge><div className="my-2 text-xs text-muted-foreground">↓</div><p className="break-words text-sm font-semibold text-primary">{to}</p>{r.toTitle&&<p className="mt-1 break-words text-xs text-muted-foreground">{r.toTitle}</p>}</div><RecordBadge record={r}/></div><p className="mt-4 break-words rounded-md bg-muted/35 p-3 text-sm">{r.reason||"No relationship rationale recorded."}</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><FieldValue label="Applicability" value={r.applicability||"Not provided"}/><FieldValue label="Mandatory" value={mandatoryLabel(r.mandatory)}/><FieldValue label="Category" value={r.category||"—"}/><FieldValue label="Status" value={readable(r.status)||"—"}/></div></div>}

export function SharedRelationshipsPage(){const {records,loading,error}=useSharedRecords<RelationshipRecord>("relationships");const [q,setQ]=useState("");const filtered=records.filter(r=>searchText(r.fromStandard,r.toStandard,r.toTitle,r.relationshipType,r.reason,r.category,r.domain).includes(q.toLowerCase()));return <Shell title="Standards Relationships" description="Shared allied, normative, safety and test-method relationships."><Panel><FilterBar placeholder="Search standard, relationship or reason…" onSearch={setQ}/>{error&&<div className="mb-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load {DATA_MODE} relationships. {error}</div>}{loading?<p className="text-sm text-muted-foreground">Loading relationships…</p>:filtered.length?<div className="grid gap-4 lg:grid-cols-2">{filtered.map(r=><RelationshipCard key={r.id} r={r}/>)}</div>:<EmptyState title="No relationships available" description={`No shared relationships are currently available in ${DATA_MODE}.`}/>}</Panel></Shell>}

function CertificationCard({r}:{r:CertificationRecord}){return <div className="rounded-lg border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-navy">{r.type||"Certification record"}</h3><p className="mt-1 break-words text-xs text-muted-foreground">{r.isNumber||r.standardId||r.title||"No standard identity"}</p></div><RecordBadge record={r}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><FieldValue label="Scheme" value={r.scheme||"Not provided"}/><FieldValue label="Mandatory" value={mandatoryLabel(r.mandatory)}/><FieldValue label="Status" value={readable(r.status)||"Not provided"}/><FieldValue label="Authority / Source" value={r.authority||r.sourceId||"Not provided"}/><FieldValue label="Category" value={r.category||"—"}/><FieldValue label="Verification" value={r.sourceVerified===true?"Verified reference":r.sourceVerified===false?"Unverified":"Not established"}/></div></div>}
function QcoCard({r}:{r:QcoRecord}){return <div className="rounded-lg border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-navy">{r.name||"QCO record"}</h3><p className="mt-1 break-words text-xs text-muted-foreground">{r.isNumber||r.standardId||"No standard identity"}</p></div><RecordBadge record={r}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><FieldValue label="Status" value={readable(r.status)||"Not provided"}/><FieldValue label="Ministry" value={r.ministry||"Not provided"}/><FieldValue label="Notification Date" value={r.notificationDate||"Not provided"}/><FieldValue label="Effective Date" value={r.effectiveDate||"Not provided"}/><FieldValue label="Source" value={r.sourceId||"Not provided"}/><FieldValue label="Verification" value={r.sourceVerified===true?"Verified reference":r.sourceVerified===false?"Unverified":"Not established"}/></div></div>}

export function SharedCertificationPage(){const certs=useSharedRecords<CertificationRecord>("certifications");const qcos=useSharedRecords<QcoRecord>("qcos");const error=certs.error||qcos.error;return <Shell title="Certification & QCO" description="Shared certification and QCO knowledge for the selected dataset.">{error&&<div className="mb-4 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load complete compliance data. {error}</div>}<div className="grid gap-5 xl:grid-cols-2"><Panel title="Certifications">{certs.loading?<p className="text-sm text-muted-foreground">Loading certifications…</p>:certs.records.length?<div className="space-y-3">{certs.records.map(r=><CertificationCard key={r.id} r={r}/>)}</div>:<EmptyState title="No certifications" description={`No certification records are loaded in ${DATA_MODE}.`}/>}</Panel><Panel title="QCO Records">{qcos.loading?<p className="text-sm text-muted-foreground">Loading QCO records…</p>:qcos.records.length?<div className="space-y-3">{qcos.records.map(r=><QcoCard key={r.id} r={r}/>)}</div>:<EmptyState title="No QCO records" description={`No QCO records are loaded in ${DATA_MODE}.`}/>}</Panel></div></Shell>}

function VersionCard({r}:{r:VersionRecord}){return <div className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-sm font-semibold text-primary">{r.isNumber||r.standardId||"Unknown standard"}</p><h3 className="mt-1 break-words font-semibold text-navy">{r.title||"Version record"}</h3><p className="mt-1 text-xs text-muted-foreground">{r.category||"Unclassified"}</p></div><RecordBadge record={r}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><FieldValue label="Current Version" value={r.currentVersion||"Not provided"}/><FieldValue label="Version Status" value={r.status||"Not provided"}/><FieldValue label="Reaffirmed" value={r.reaffirmed||"Not provided"}/><FieldValue label="Record Type" value={readable(r.recordType)||"Version status"}/></div><div className="mt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Amendments</p>{r.amendments?.length?<div className="space-y-2">{r.amendments.map((a,i)=><div key={i} className="break-words rounded-md border bg-muted/25 p-2 text-sm">{typeof a==="string"?a:String((a as any).title||(a as any).description||"Amendment record")}</div>)}</div>:<p className="text-sm text-muted-foreground">No amendments recorded</p>}</div>{r.standardId&&<div className="mt-4"><Button size="sm" variant="outline" asChild><a href={standardHref(r.standardId)}>View Standard</a></Button></div>}</div>}

export function SharedAmendmentsPage(){const {records,loading,error}=useSharedRecords<VersionRecord>("amendments");const [q,setQ]=useState("");const filtered=records.filter(r=>searchText(r.standardId,r.isNumber,r.title,r.currentVersion,r.status,r.category,r.amendments).includes(q.toLowerCase()));return <Shell title="Amendments & Versions" description="Shared amendment and version records."><Panel><FilterBar placeholder="Search IS number, title, version or category…" onSearch={setQ}/>{error&&<div className="mb-3 rounded-md border border-warning/25 bg-warning-soft p-3 text-xs text-warning">Unable to load {DATA_MODE} amendment/version data. {error}</div>}{loading?<p className="text-sm text-muted-foreground">Loading amendment and version records…</p>:filtered.length?<div className="grid gap-4 lg:grid-cols-2">{filtered.map(r=><VersionCard key={r.id} r={r}/>)}</div>:<EmptyState title="No amendments or versions available" description={`No shared amendment/version records are currently available in ${DATA_MODE}.`}/>}</Panel></Shell>}
