import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, BadgeCheck, BarChart3, BookOpen, Boxes, CircleAlert, FileCheck2, Search, ShieldCheck, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DEMO_MODE, setDemoMode } from "@/lib/demo-mode";
import { AppShell, DataTable, EmptyState, PageHeader, Panel, StatusBadge } from "./ui";
import { useAuth } from "@/contexts/AuthContext";
import { listAnalysesForUser, type SavedAnalysisRecord } from "@/lib/analysis-storage";
import { useSharedRecords } from "@/lib/knowledge-base";

const iconMap = { BookOpen, BadgeCheck, Boxes, FileCheck2, ShieldCheck, CircleAlert };
export function DashboardPage() {
 const navigate=useNavigate();
 const { user }=useAuth();
 const [recent,setRecent]=useState<SavedAnalysisRecord[]>([]);
 const standardsKb=useSharedRecords<any>("standards"); const productsKb=useSharedRecords<any>("products"); const categoriesKb=useSharedRecords<any>("categories");
 const relationshipsKb=useSharedRecords<any>("relationships"); const certificationsKb=useSharedRecords<any>("certifications"); const qcosKb=useSharedRecords<any>("qcos"); const submissionsKb=useSharedRecords<any>("submissions");
 useEffect(()=>{if(user) void listAnalysesForUser(user.uid).then(records=>setRecent(records.slice(0,5)))},[user?.uid]);
 const liveMetrics=[
  {label:"Standards",value:standardsKb.records.length,detail:"Shared standards in active dataset",icon:"BookOpen"},
  {label:"Products",value:productsKb.records.length,detail:"Canonical product mappings",icon:"Boxes"},
  {label:"Categories",value:categoriesKb.records.length,detail:"Shared taxonomy categories",icon:"BadgeCheck"},
  {label:"Relationships",value:relationshipsKb.records.length,detail:"Allied/normative relationships",icon:"FileCheck2"},
  {label:"Certification / QCO",value:certificationsKb.records.length+qcosKb.records.length,detail:"Regulatory records",icon:"ShieldCheck"},
  {label:"Needs Review",value:submissionsKb.records.filter((r:any)=>["PENDING","NEEDS_REVIEW","NEEDS_CORRECTION"].includes(String(r.status||""))).length,detail:"Pending shared submissions",icon:"CircleAlert"},
 ];
 const domainCounts=Object.entries(standardsKb.records.reduce((acc:Record<string,number>,r:any)=>{const d=String(r.classification?.domain||r.domain||"Unclassified");acc[d]=(acc[d]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]).slice(0,6);
 const maxDomain=Math.max(1,...domainCounts.map(([,v])=>v));
 const healthCounts={verified:standardsKb.records.filter((r:any)=>String(r.verificationStatus||r.provenance?.verificationStatus||"").includes("VERIFIED")).length,review:standardsKb.records.filter((r:any)=>String(r.verificationStatus||r.status||"").includes("REVIEW")).length,inactive:standardsKb.records.filter((r:any)=>String(r.status?.state||r.status||"").toUpperCase().includes("INACTIVE")).length};
 return <AppShell><PageHeader title="Procurement Standards Intelligence" description="Identify applicable Indian Standards and procurement compliance requirements using AI-assisted analysis." actions={<><Button variant="outline" asChild><Link to="/standards"><Search/>Search Standards</Link></Button><Button asChild><Link to="/analyze"><FileCheck2/>Analyze New Tender</Link></Button></>}/>
 <div className="mb-4 flex flex-col justify-between gap-3 rounded-md border-2 border-primary/20 bg-card px-4 py-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-navy">Dataset Mode</p><StatusBadge tone={DEMO_MODE?"warning":"success"}>{DEMO_MODE?"DEMO ON":"REAL MODE"}</StatusBadge></div><p className="mt-1 text-xs text-muted-foreground">Demo data is visible only while DEMO is selected. REAL hides every built-in demo record.</p></div><div className="flex gap-2"><Button type="button" variant={DEMO_MODE?"default":"outline"} onClick={()=>setDemoMode(true)}>Enable Demo</Button><Button type="button" variant={!DEMO_MODE?"default":"outline"} onClick={()=>setDemoMode(false)}>Disable Demo / Real</Button></div></div>
 <div className="mb-4 flex items-center justify-between rounded-md border border-dashed bg-card px-4 py-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-md bg-secondary text-primary"><Upload className="h-4 w-4"/></div><div><p className="text-sm font-medium">Quick upload</p><p className="text-xs text-muted-foreground">PDF, DOCX, XLSX, CSV or scanned tender</p></div></div><Button size="sm" variant="outline" asChild><Link to="/analyze">Upload Tender</Link></Button></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{liveMetrics.map((m,i)=>{const Icon=iconMap[m.icon as keyof typeof iconMap];return <div key={m.label} className="app-card p-4"><div className="mb-3 flex items-center justify-between"><div className="grid h-8 w-8 place-items-center rounded-md bg-secondary text-primary"><Icon className="h-4 w-4"/></div>{i===5?<StatusBadge tone="warning">Review</StatusBadge>:<span className="text-[10px] text-success">● Firestore</span>}</div><div className="text-2xl font-semibold text-navy">{m.value}</div><p className="mt-1 text-xs font-medium">{m.label}</p><p className="mt-2 text-[11px] text-muted-foreground">{m.detail}</p></div>})}</div>
 {!DEMO_MODE&&<div className="mt-5 rounded-md border border-dashed bg-card p-8 text-center"><p className="font-semibold text-navy">No dataset loaded</p><p className="mt-1 text-sm text-muted-foreground">DEMO mode is disabled. The dashboard will remain empty until verified real data is loaded.</p></div>}<div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><Panel title="Recent Analyses" description="Your latest explicitly saved analyses" action={<Button size="sm" variant="ghost" asChild><Link to="/history">View all <ArrowRight/></Link></Button>} className="overflow-hidden">{recent.length?<div className="-m-5"><DataTable columns={["Source / Query","Product","Recommended Standard","Confidence","Mode","Status","Saved At","Action"]} rows={recent.map(a=>[<div><p className="max-w-52 truncate font-medium">{a.sourceName}</p><p className="text-[11px] text-muted-foreground">{a.analysisId}</p></div>,a.product,<span className="font-medium text-primary">{a.primaryStandard}</span>,<span className="font-semibold">{a.confidence==null?"—":`${a.confidence}%`}</span>,<StatusBadge tone={a.dataMode==="DEMO"?"warning":"success"}>{a.dataMode}</StatusBadge>,<StatusBadge>{a.status}</StatusBadge>,new Date(a.savedAt).toLocaleString(),<Button size="sm" variant="ghost" onClick={()=>navigate("/results",{state:{analysis:a.analysis,parsedDocument:null,sourceText:""}})}>View</Button>])}/></div>:<EmptyState title="No saved analyses yet" description="Run an analysis and click Save Analysis. Your latest saved records will appear here."/>}</Panel>
 <div className="space-y-5"><Panel title="Standards by Domain" description="Live standard counts from the active Firestore dataset"><div className="space-y-4">{domainCounts.length?domainCounts.map(([label,value])=><div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span>{label}</span><span className="font-semibold">{value} standards</span></div><div className="h-2 overflow-hidden rounded-sm bg-muted"><div className="h-full bg-primary" style={{width:`${Math.max(6,(Number(value)/maxDomain)*100)}%`}}/></div></div>):<p className="text-sm text-muted-foreground">No standards loaded in the active dataset.</p>}</div></Panel>
 <Panel title="Knowledge Base Health" description="Live Firestore record status"><div className="grid grid-cols-2 gap-3">{[["Verified",healthCounts.verified,"success"],["Needs Review",healthCounts.review,"warning"],["Inactive",healthCounts.inactive,"neutral"],["Pending Submissions",liveMetrics[5].value,"warning"]].map(([l,v,t])=><div key={String(l)} className="rounded-md border bg-muted/30 p-3"><StatusBadge tone={t as never}>{l}</StatusBadge><p className="mt-2 text-xl font-semibold text-navy">{v}</p></div>)}</div></Panel></div></div>
 </AppShell>
}
